---

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: run nginx
  service:
     name: nginx
     state: started

- name: replace conf for header
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  register: confupdated_server

- name: deploy helloworld json
  copy:
    src: sample.json
    dest: /usr/share/nginx/html/ 
  

- name: restart nginx
  service: name=nginx state=restarted
  when: confupdated_server.changed 
